### ISSUE TITLE
Questions about DBManager

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/pyre#6]
I have some questions about some things in the DBManager.py file (/pyre/python/pyre/db/DBManager.py).

First, on line 49, there is the following syntax:
```
", ".join([%s] * len(columns)
```
What is this doing? I'm trying to convert this to Python 3-style string formatting, but, since there's a `*` instead of a `%`, I'm not sure how to do that.

Also, on line 76, there is this:
```
"%s=%%s" % ...
```
What does `%%s` do? I know how to convert the first part (`%s`), but I'm not sure about the second one (`%%s`).

**Comment by yxqd** [comment]
["%s"] is a list of strings. list*N is a longer list with repetitions of original list. For example [1,2]*3 = [1,2,1,2,1,2]. So, ["%s"] * 3 = ["%s","%s","%s'].  

", ".join(str_list)  creates a new string that joins the strings in the str_list using ", ". See https://www.tutorialspoint.com/python/string_join.htm for more details.

So the whole ", ".join([%s] * len(columns) is used to create a string `"%s, %s, %s, ..., %s"` where there are len(columns) copies of `%s`.

You just need to change is "%s" -> "{}", so that the code generates `"{}, {}, ..., {}"` where there are len(columns) copies of `{}`.

**Comment by yxqd** [comment]
In "%%s" the first "%" is used to escape the second "%".

Similarly, you can use "{{ }}" in format strings, and the formatting result would be "{ }".
